version: '3.7'

services:
  api:
    image: rg.fr-par.scw.cloud/oppp/openpush-api:latest
    volumes:
      - type: volume
        source: openpush-data
        target: /data
    networks:
      - openpush
    environment:
      DEBUG: "true"
    secrets:
      - api_admin_username
      - api_admin_password
  push:
    image: rg.fr-par.scw.cloud/oppp/open-poussepousse:latest
    volumes:
       - "openpush-data:/data"
    ports:
      - "5001:5001"
    environment:
      DEBUG: "true"
    depends_on:
      - "api"
  nginx:
    image: nginx:alpine
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - openpush
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - "certbot-data:/etc/letsencrypt"
      - "certbot-www:/var/www/certbot"
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew -w /var/www/certbot; sleep 12h & wait $${!}; done;'"
    volumes:
      - "certbot-data:/etc/letsencrypt"
      - "certbot-www:/var/www/certbot"

secrets:
  api_admin_username:
    external: True
    name: 'openpush_api_admin_username'
  api_admin_password:
    external: True
    name: 'openpush_api_admin_password'

volumes:
  openpush-data:
  certbot-data:
  certbot-www:

networks:
    openpush:
